# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='服务器名称')),
                ('ip', models.CharField(max_length=15, verbose_name='服务器ip地址')),
                ('type', models.IntegerField(choices=[(1, 'web服务器'), (2, '数据库服务器'), (3, '缓存服务器')], verbose_name='服务器类型')),
                ('status', models.IntegerField(choices=[(0, 'offline'), (1, 'online')], default=0, verbose_name='服务器状态')),
            ],
            options={
                'verbose_name': '服务器信息列表',
                'db_table': 'hostlist',
            },
        ),
    ]
