# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图书名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='图书价格')),
            ],
            options={
                'verbose_name': '图书信息',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='出版社名称')),
                ('address', models.CharField(max_length=50, verbose_name='出版社地址')),
            ],
            options={
                'verbose_name': '出版社信息',
                'db_table': 'publish',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.Publish'),
        ),
    ]
