# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_auto_20190804_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app03.Publish'),
        ),
    ]
